import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright'),browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];let current;
page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/cross-harness-coordinator/snapshot'))current=r.postDataJSON().payload.sessionId;});
const rpc=async(channel,method,payload)=>page.evaluate(async({channel,method,payload})=>{const r=await fetch(channel+'/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'client-request',rpcId:crypto.randomUUID(),method,payload})});return {status:r.status,body:await r.json()};},{channel,method,payload});
try{
await page.goto(process.env.COORDINATOR_TEST_URL,{waitUntil:'networkidle'});if(await page.getByRole('button',{name:'继续',exact:true}).count()){await page.getByRole('button',{name:'继续',exact:true}).click();await page.waitForTimeout(200);}if(await page.getByRole('button',{name:'稍后配置',exact:true}).count())await page.getByRole('button',{name:'稍后配置',exact:true}).click();
const created=await rpc('/api','workspace/create',{args:{request:{path:path.resolve('test-data/native-workspace')}}});assert.equal(created.body.result.ok,true);const session=await rpc('/api','session/create',{args:{request:{workspaceId:created.body.result.value.workspace.workspaceId}}});assert.equal(session.body.result.ok,true);await page.getByText('native-workspace',{exact:true}).first().click();await page.waitForTimeout(400);
await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'协调器',exact:true}).click();await page.waitForTimeout(300);const copy=page.getByRole('button',{name:'复制接入邀请',exact:true}).first();if(!await copy.isVisible())await page.getByText('接入与运行设置',{exact:true}).click();assert.equal(await copy.isEnabled(),true);await copy.click();await page.getByRole('button',{name:'取消邀请',exact:true}).waitFor();assert.ok(current);
const desktop=await rpc('/cross-harness-coordinator','invite',{sessionId:current,origin:'dsh-app://app'});assert.equal(desktop.body.result.ok,true);const snapshot=(await rpc('/cross-harness-coordinator','snapshot',{sessionId:current})).body.result.value;assert.equal(snapshot.invitation.state,'waiting');const invitation=snapshot.invitation;assert.equal(JSON.parse(fs.readFileSync(invitation.file)).url,new URL(process.env.COORDINATOR_TEST_URL).origin+'/coordinator-invite/submit');const response=path.resolve('test-data/native-onboarding-response.json');fs.writeFileSync(response,JSON.stringify({label:'隔离回传测试端',version:'fixture-1',definition:{command:process.execPath,args:[path.resolve('test/fixture.mjs'),'text','native-test.txt'],protocol:'text'}}));
const {stdout}=await promisify(execFile)(process.execPath,[path.resolve('lib/invite-client.mjs'),'--invitation',invitation.file,'--response',response],{windowsHide:true,timeout:10000});assert.match(stdout,/已自动接入/);const after=(await rpc('/cross-harness-coordinator','snapshot',{sessionId:current})).body.result.value;assert.equal(after.invitation.state,'connected');assert.ok(after.endpoints.some(e=>e.label==='隔离回传测试端'));assert.equal(fs.existsSync(invitation.file),false);await page.waitForTimeout(2200);assert.equal(await page.getByRole('button',{name:'确认接入',exact:true}).count(),0);
await page.getByText('接入与运行设置',{exact:true}).click();await page.getByRole('spinbutton').fill('0');await page.getByRole('button',{name:'保存运行设置',exact:true}).click();await page.getByText('并发须为1至4',{exact:true}).waitFor();assert.equal(await page.getByText('connection: invalid server-response failure',{exact:true}).count(),0);await page.getByRole('spinbutton').fill('3');await page.getByRole('button',{name:'保存运行设置',exact:true}).click();await page.waitForTimeout(300);assert.equal((await rpc('/cross-harness-coordinator','settings',{})).body.result.value.concurrency,3);assert.deepEqual(errors,[]);await page.screenshot({path:path.resolve('test-data/native-settings-expanded.png')});console.log(JSON.stringify({passed:true,coverage:['最终包原生设置栏目','空白会话绑定','复制邀请','桌面origin不会污染回传地址','客户端回传即自动登记','无需人工确认','合法错误由真实客户端显示','设置保存'],current,errors},null,2));
}finally{await browser.close();}
